export enum NotesActions {
  CREATE_NOTE = 'CREATE_USER',
  DELETE_NOTE = 'DELETE_USER',
  UPDATE_NOTE = 'UPDATE_USER',
  GET_ALL_NOTES = 'GET_ALL_USERS',
  GET_NOTES_BY_USERID = 'GET_NOTES_BY_USERID',
  DELETE_NOTES_BY_USERID = 'DELETE_NOTES_BY_USERID',
  GET_NOTE = 'GET_NOTE',
}
