export enum NotesActions {
  CREATE_NOTE = 'CREATE_NODE',
  DELETE_NOTE = 'DELETE_NODE',
  UPDATE_NOTE = 'UPDATE_NODE',
  GET_ALL_NOTES = 'GET_ALL_NODES',
  GET_NOTES_BY_USERID = 'GET_NOTES_BY_NODEID',
  DELETE_NOTES_BY_USERID = 'DELETE_NOTES_BY_NODEID',
  GET_NOTE = 'GET_NOTE',
}
